_inputs: 
  page_blocks:
    type: array
    options:
      structures: _structures.page_blocks      
  blocks:
    options:
      preview:
          subtext:
            - key: label 
  template:
    hidden: true         

  include_left-hand_column_text_:
    type: checkbox
    label: Show Lefthand Text?

  lefthand_text:
    type: group
    label: Lefthand Text
    options:
      collapsed: false

  lefthand_text.header_type:
    type: select
    options:
      values:
        - Large Header
        - Medium Header
        - Small Header
        - Film/Book Title
        - Link
        - Text with Download

  lefthand_text.text:
    type: markdown

  lefthand_text.download:
    type: text

  lefthand_text.link_url:
    type: text

collections_config:
  data:
    filter:
      exclude:
        - nav.yaml
  pages:
    schemas:
      _unlisted: true
    _enabled_editors:
      - data
    _inputs:  
      homepage:
        hidden: true   
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true 
      description:
        type: textarea
        label: Page Description (for SEO)
  bbw-juries:
    name: "BBW: Juries"
    _enabled_editors:
      - data  
    _inputs:      
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true     
  bbw-projects:
    name: "BBW: Projects"
    _enabled_editors:
      - data
    _inputs:      
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true  
      project_categories:
        hidden: true  
  bbw-years:
    name: "BBW: Years"     
    _enabled_editors:
      - data     
    _inputs:      
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true  
  films:
    _enabled_editors:
      - data
    _inputs:   
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true
  programs:
    _enabled_editors:
      - data  
    _inputs:
      date:
        hidden: true
      $.title:
        hidden: true  
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true
      description:
        hidden: true
      section_break:
        hidden: true
      template:
        hidden: true    
      show_bbw_slideshow:
        label: Show Slideshow
        type: checkbox        
      bbw-slideshow-images:
        label: BBW Slideshow Images                            
  resources:
    _enabled_editors:
      - data
    _inputs:  
      date:
        hidden: true 
      layout:
        hidden: true
      navCategory:
        hidden: true 
      permalink:
        hidden: true   
  podcasts:
    _enabled_editors:
      - data      
    _inputs:
      navCategory:
        hidden: true
      layout:
        hidden: true     
  emerging-leaders:
    schemas:
      default:
        path: schemas/emerging-leaders.md
    _enabled_editors:
      - data      
    _inputs:
      navCategory:
        hidden: true
      layout:
        hidden: true
      template:
        hidden: true
      section_break:
        hidden: true      
      text_block:
        type: textarea
      date:
        type: date
      description:
        hidden: true   
  emerging-firms:
    schemas:
      default:
        path: schemas/emerging-firms.md
    _enabled_editors:
      - data      
    _inputs:
      navCategory:
        hidden: true
      layout:
        hidden: true
      template:
        hidden: true
      section_break:
        hidden: true      
      text_block:
        type: textarea
      date:
        type: date
      description:
        hidden: true               

collection_groups:
  - heading: Pages
    collections:
      - pages
      - resources
      - programs
  - heading: Built by Women 
    collections:   
      - bbw-years
      - bbw-projects
      - bbw-juries
  - heading: Collections 
    collections:     
      - podcasts
      - emerging-leaders
      - emerging-firms   

_structures:
  page_blocks:
    id_key: template
    values:
      - label: Text Block
        preview:
          text: Text Block
          subtext:
            - key: text_block 
              empty_value: ""
          icon: article
        value:
          template: text-block
          text_block: ""
          section_break: false
          include_left-hand_column_text_: false
          lefthand_text:
            header_type: Large Header
            text: ''
            download: ''
            link_url: ''
          section_break: false
        _inputs:
          text_block:
            type: markdown
          section_break:
            hidden: true
          label:
            hidden: true
      - label: Buttons
        preview:
          text: Buttons
          subtext:
          icon: smart_button
        value:
          template: buttons-block
          buttons_header__optional_: ''
          button:
            - button_text:
              button_link:
          section_break: false
          include_left-hand_column_text_: false
        _inputs:
          icon:
            hidden: true
          buttons_header__optional_:
            label: Buttons Header (optional)
            type: text
          button:
            hidden: false
          section_break:
            hidden: true
          include_left-hand_column_text_:
            hidden: true
      - label: Image
        preview:
          text: Image
          image:
            - key: image
          icon: image
        value:
          template: image-block
          image:
          section_break: false
          image_caption_text:
          alt_text:   
          include_left-hand_column_text_: false
          lefthand_text:
            header_type: Large Header
            text: ''
            download: ''
            link_url: ''
          section_break: false
        _inputs:
          section_break:
            hidden: true
          label:
            hidden: true  
      - label: Miscellaneous Block
        preview:
          text: Miscellaneous Block
          subtext:
            - key: miscellaneous
              empty_value: ""
          icon: article
        value:
          template: miscellaneous-block
          miscellaneous: ""
          section_break: false
          include_left-hand_column_text_: false
          lefthand_text:
            header_type: Large Header
            text: ''
            download: ''
            link_url: ''
          section_break: false
        _inputs:
          miscellaneous:
            type: markdown
          section_break:
            hidden: true
          label:
            hidden: true              
      - label: Code Block
        preview:
          text: Code Block
          subtext:
            - text: 'Code for custom HTML, like iframes or embeds'
          icon: article
        value:
          template: code-block
          code_block: ''
          include_left-hand_column_text_: false
          lefthand_text:
            header_type: Large Header
            text: ''
            download: ''
            link_url: ''
          section_break: false
        _inputs:
          code_block:
            type: code
            options:
              language: html
          section_break:
            hidden: false
          label:
            hidden: true     
      - label: Media Gallery
        preview:
          text: Media Gallery
          subtext:
            - text: 'Add images that link out to videos'
          icon: article
        value:
          template: media-gallery-block
          media:
            - image: ''
              title: ''
              link_to_video: ''
          include_left-hand_column_text_: false
          lefthand_text:
            header_type: Large Header
            text: ''
            download: ''
            link_url: ''
          section_break: false
        _inputs:
          section_break:
            hidden: false
          label:
            hidden: true                                                  
             