---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: about
  label: About
  create: all
  match: "**/*"
  templates:
  - main-two-up
- type: directory
  path: _resources
  label: Resources
  create: documents
  match: "**/*"
  templates:
  - main-two-up
- type: directory
  path: _programs
  label: Programs
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - main-two-up
- type: jekyll-pages
  label: Msc. Pages
  create: all
- type: heading
  label: Built By Women
- type: directory
  path: _bbw-years
  label: 'BBW: Years'
  create: documents
  match: "**/*"
- type: directory
  path: _bbw-projects
  label: 'BBW: Projects'
  create: documents
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/beverly-willis-architecture-foundation/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
